sudo: false
language: perl
perl:
  - "5.30"
  - "5.28"
  - "5.26"
  - "5.24"
  - "5.22"
  - "5.20"
  - "5.18"
  - "5.16"
  - "5.14"

env: LYSTYNG_DB_SERVER=127.0.0.1 LYSTYNG_DB_NAME=lystyng LYSTYNG_DB_USER=travis LYSTYNG_DB_PASS=''

before_script:
  - mysql -e 'create database lystyng;'
  - mysql -e "grant all on lystyng.* to '$LYSTYNG_DB_USER'@'localhost' identified by '$LYSTYNG_DB_PASS';"
  - mysql -D lystyng < db/lystyng.sql

install:
  - export RELEASE_TESTING=1 AUTOMATED_TESTING=1 AUTHOR_TESTING=1 HARNESS_OPTIONS=c HARNESS_TIMER=1
  - cpanm --quiet --notest Devel::Cover
  - cpanm --quiet --notest Devel::Cover::Report::Coveralls
  - cpanm --quiet --notest --installdeps .

script:
  - PERL5OPT=-MDevel::Cover=-coverage,statement,branch,condition,path,subroutine prove -lrsv t
  - cover

after_success:
  - cover +ignore ^t/ +ignore ^/home/travis -report coveralls

addons:
  mariadb: '10.3'

